config/routes.rb
InventoryManagement::Application.routes.draw do

  devise_for :users
  resources :posts, :except => [:index] do
    resources :comments, :only => [:create, :destroy]
  end

  get '/' => 'home#new'
  get 'profile/' => 'users#show'
  get 'profile/posts/' => 'posts#user_posts'
  post '/search' => 'posts#search'

  root to:"home#new"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, Post
    can [:read, :create], Comment
    cannot [:update, :destroy], Post do |post|
      post.user_id != user.id
    end
    can [:destroy], Comment do |comment|
      comment.user_id == user.id
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post, :user

  validates :body, :presence => true, :length => {minimum: 5}

  belongs_to :user
  belongs_to :post
end

app/models/concerns/post_es.rb
module PostSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end
end

app/models/post.rb
require 'concerns/post_es'
class Post < ActiveRecord::Base
  include PostSearchable

  attr_accessible :description, :title, :user
  validates :title, presence: true, length: {:minimum => 5, :maximum => 255}, uniqueness: true
  validates :description, presence: true, length: {:minimum => 10}

  belongs_to :user
  has_many :comments, :dependent => :delete_all

  after_commit :send_email_to_user

  def send_email_to_user
    UserMailer.delay.post_creation_email(self.id)
  end
end
Post.__elasticsearch__.import

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  validates :name, presence: true, length: {:minimum => 2, :maximum => 50}

  has_many :posts, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all

  before_save {email.downcase!}
  after_save :send_welcome_email

  def send_welcome_email
    if self.confirmed_at_changed?
      UserMailer.delay.welcome_email(self.id)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    render :file => "#{Rails.root}/public/422.html", :status => 422, :layout => false
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  def create
    @post = Post.find(params[:post_id])
    params[:comment][:user] = current_user
    @comment = @post.comments.create(params[:comment])
    respond_to do |format|
      format.js {render partial: "post_create"}
    end
  end

  def destroy
    Comment.destroy(params[:id])
    respond_to do |format|
      # format.html { redirect_to post_path(@post) }
      format.js   { render partial: "post_delete" }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def new
    @posts = Post.order('updated_at')
    render 'new'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  load_and_authorize_resource

  def user_posts
    @user_posts = @current_user.posts
    render 'user_posts'
  end

  def new
    @post = Post.new
    render 'new'
  end

  def create
    @post = Post.new(title: params[:post][:title], description: params[:post][:description], user: current_user)
    respond_to do |format|
      if @post.save
        format.js {render partial: "post_create"}
      else
        # format.html { render :action => "new" }
        format.js {render :action => "new"}
      end
    end
  end

  def show
    @post = Post.eager_load(:comments).find_by_id(params[:id])
    raise ActionController::RoutingError.new('Not Found') if @post.blank?
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    respond_to do |format|
      # format.html { redirect_to profile_posts_path }
      format.js   { render partial: "post_delete" }
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.js {render partial: "post_create"}
      else
        # format.html {render :action => "edit"}
        format.js {render :action => "new"}
      end
    end
  end

  def search
    @posts = Post.search(params[:search]).records
    respond_to do |format|
      format.js {render partial: "post_search"}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  def show
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mailer_logger
    MailerLogger.new.logger
  end
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <p>
    <b>Commenter:</b>
    <%= comment.user.name %>(<i><%= comment.user.email %></i>)
  </p>

  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Remove Comment', [comment.post, comment], :confirm => 'Are you sure?',
                :method => :delete, :id => 'delete-comment', :remote => true if user_signed_in? && (can? :destroy, comment) %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], :remote => true) do |f| %>
  <div id="comment-body-add">
    <%= f.text_area :body, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit "Add Comment", disable_with: "Submitting.." %>
  </div>
<% end %>

app/views/comments/_post_create.js.erb
$('#post-comments').append('<%= j (render partial: "comment", object: @comment) %>');
$("#comment-body-add textarea").val("");

app/views/comments/_post_delete.js.erb
$('#delete-comment').bind('ajax:success', function() {
    $('#comment_<%= @comment.id %>').fadeOut();
});

app/views/home/_posts_table.html.erb
<% if @posts.any? %>
  <h1>Recently added/updated blogs</h1>

  <table id="post-table">
    <tr>
      <td>
        <b>Title</b>
      </td>
      <td>
        <b>Updated Datetime</b>
      </td>
    </tr>
    <% @posts.each do |post| %>
      <tr class="post-row">
        <td>
          <%= link_to post.title, post_path(post) %>
        </td>
        <td>
          <%= post.updated_at %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <i>No blogs posts exist..</i>
<% end %>

app/views/home/new.html.erb
<%= form_tag(search_path, :remote => true, :id => 'search-form') do %>
  <%= search_field_tag :search, params[:search], placeholder: "Search", required: true %>
  <div>
    <%= button_tag "Search" %>
  </div>
<% end %>
<div id="posts-data">
  <%= render 'posts_table', object: @posts %>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
        <%= link_to "Profile", profile_path %>
    </li>
    <li>
      <%= link_to "New Post", new_post_path %>
    </li>
    <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </li>
  </ul>
<% else %>
  <ul>
    <li>
      <%= link_to "Login", user_session_path %>
    </li>
    <li>
      <%= link_to "Signup", new_user_registration_path %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryManagement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%#= render 'layouts/footer' %>
    <%#= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :remote => true) do |f|  %>
  <div id="post-title">
    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>
    <p id="title-error"></p>
  </div>
  <br>
  <div id="post-description">
    <%= f.label :description %>
    <%= f.text_area :description, :required => true %>
    <p id="description-error"></p>
  </div>
  <br>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post_create.js.erb
window.location.replace("<%= post_path(@post) %>");

app/views/posts/_post_delete.js.erb
window.location.replace("<%= profile_posts_path %>");

app/views/posts/_post_search.js.erb
$('#search-form').bind('ajax:success', function() {
    $('#posts-data').empty().append("<%= escape_javascript("#{render partial: 'home/posts_table'}").html_safe %>");
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div id="new-post-form">
  <%= render 'form' %>
</div>

app/views/posts/new.js.erb
<% if @post.errors.messages[:title] %>
  $('#post-title #title-error').html('<p>Title <%= @post.errors.messages[:title][0] %></p>')
<% end %>
<% if @post.errors.messages[:description] %>
$('#post-description #description-error').html('<p>Description <%= @post.errors.messages[:description][0] %></p>')
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.description %></p>

<h2>Comments</h2>
<% if !@post.comments.any? %>
  <i>No comments..</i>
<% end %>
<div id="post-comments">
  <%= render @post.comments %>
</div>

<h3>Add a comment</h3>
<%= render "comments/form" %>

<%= link_to "Edit Post", edit_post_path(@post) if user_signed_in? && (can? :update, @post) %>
<%= link_to "Delete Post", post_path, :confirm => "Are you sure you want to delete post?",
            :method => :delete, :remote=>true if user_signed_in? && (can? :destroy, @post) %>

app/views/posts/user_posts.html.erb
<h2>Your Posts</h2>
<%= link_to "New Post", new_post_path %>
<% @user_posts.each do |user_post| %>
  <li>
    <%= link_to user_post.title,  post_path(user_post) %>
  </li>
<% end %>

app/views/users/show.html.erb
<h2>Welcome, </h2> <h3> <%= current_user.email %> </h3>
<%= link_to "Posts", profile_posts_path %>
<%= link_to "New Post", new_post_path %>